version: "3.1"
services:
  php:
    container_name: raizes_laravel_api
    build: .
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/
    networks:
      - default
    
