version: "3.1"
services:
  nginx-laratest:
    container_name: raizes_laravel_nginx
    build: ./nginx
    restart: on-failure
    volumes:
      - ./:/var/www
      
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - raizes_api
  api:
    container_name: raizes_laravel_api
    restart: on-failure
    build: ./api
    ports:
      - "3333:80"
      - "3334:443"
    volumes:
      - ./:/var/www/html/
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./nginx/nginx.d/:/etc/nginx/conf.d/
      - ./nginx/nginx/zt.conf/:/etc/nginx/conf.d/
      - ./nginx/nginx/zt.conf/:/etc/nginx/sites-enable/
    networks:
      - raizes_api
  
networks:
  raizes_api:
    driver: bridge

